# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  database: db/development.db

test:
  adapter: sqlite3
  database: db/test.db

production:
  adapter: postgresql
  database: imaginary-friends-forum
  url: <%= ENV['DATABASE_URL'] %>
  host: localhost
  pool: 5
  timeout: 5000
